### PR TITLE
ampersand encoding fixes

### PR DESCRIPTION
**Pull request by jgrubb16**
**Type of change**:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### Fix for #109 & #110
Builds on the work started in #124. Notably, my changes cause @coffeemakr's added tests to pass. 
I noticed this regex pattern was repeated multiple times, so I chose to define it once for import. Not married to this approach. Open to your thoughts.

### CODE REVIEW

**Review by aim97 — APPROVED** [review]

**Review by tharseken — APPROVED** [review]
LGTM

**Comment by andrenarchy** [comment]
@oozcitak Would you mind merging and releasing this fix? Thanks! :raised_hands:

**Comment by universalhandle** [comment]
Hello, folks. I'm a new co-maintainer for `xmlbuilder2`. I'll slowly be making my way through the backlog of pull requests and issues.

I've been talking with @oozcitak about transitioning some maintenance responsibilities to me, and as soon as I'm added as a maintainer on npm I'll ship this bug fix, which I've been using in production for several months.

**Comment by benasher44** [comment]
Exciting! This might also fix #117

**Pull request merged**
